
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - discourse.oconnormi.io
  resources:
  - discourses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discourse.oconnormi.io
  resources:
  - discourses/finalizers
  verbs:
  - update
- apiGroups:
  - discourse.oconnormi.io
  resources:
  - discourses/status
  verbs:
  - get
  - patch
  - update
